package dontmover.test_task;
/* if the connection has been broken or is invalid this exception is raised
*  So far it is not filled in as required, but in the future I will fix that, at least I hope
* By DonTMover
*/
public class ConnectionException extends Exception{
    public ConnectionException(){

    }
}
